server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instace:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
